// Hellom API client, split by module. Public surface is identical to the
// former single-file src/lib/hellomApi.ts.
export {
  HELLOM_API_BASE,
  HELLOM_REALTIME_PUBLIC_URL,
  clearSession,
  getActiveOutletEventName,
  getActiveOutletId,
  getImageUrl,
  getSessionEventName,
  getSessionPosAccess,
  getSessionUser,
  getToken,
  isPosCashier,
  setActiveOutletId,
  setSession,
} from './client';
export type { ApiProblem, PosAccess } from './client';
export { ApiError } from './client';
export {
  changePassword,
  forgotPassword,
  getAuthMe,
  login,
  logout,
  register,
  resetPassword,
  ssoLogin,
  updateProfile,
} from './auth';
export {
  acceptOrganizationInvitation,
  createOrganizationInvitation,
  getCurrentOrganization,
  getOrganizationDetail,
  getOrganizationInvitations,
  getOrganizationTeam,
  getOrganizations,
  inviteOrganizationMember,
  removeOrganizationMember,
  resendOrganizationInvitation,
  revokeOrganizationInvitation,
  switchOrganization,
  updateOrganizationOutletLimit,
} from './organizations';
export {
  getMemberDashboardCards,
  pollAppEntitlement,
  pollWalletBalance,
} from './member';
export {
  approvePayoutProfile,
  checkoutConfirmMock,
  checkoutConfirmWallet,
  checkoutIntentMock,
  checkoutStart,
  createWalletTopupSession,
  getAdminPayoutProfiles,
  getAutoRenewPreview,
  getCatalogApps,
  getCheckoutRuntimeConfig,
  getPaymentGatewayStatus,
  getPayoutPolicy,
  getPayoutProfile,
  getPricingMatrix,
  getRealtimeToken,
  getWalletOverview,
  getWalletTransactions,
  reconcileCheckout,
  rejectPayoutProfile,
  requestWithdrawal,
  submitPayoutProfile,
  updateCheckoutRuntimeConfig,
  walletTopupMock,
} from './billing';
export {
  approveAdminManualCheckout,
  approveWithdrawal,
  createAdminPlan,
  createAdminPromo,
  createPlatformPayout,
  deleteAdminPlan,
  deleteAdminPromo,
  deleteAdminUser,
  executeOwnerNotificationAction,
  getAdminApps,
  getAdminDashboardStats,
  getAdminMailSettings,
  getAdminManualCheckouts,
  getAdminManualPaymentConfig,
  getAdminNotifications,
  getAdminNotificationsUnreadCount,
  getAdminOrganizations,
  getAdminPaymentGatewayConfig,
  getAdminPayoutQueue,
  getAdminPlans,
  getAdminPromos,
  getAdminUserDetail,
  getAdminUsers,
  getFinanceSummary,
  getOwnerNotificationDetail,
  getPlatformFinanceSummary,
  ignoreOwnerNotificationAction,
  markAdminNotificationAsRead,
  markAllAdminNotificationsAsRead,
  markWithdrawalFailed,
  markWithdrawalPaid,
  overrideEntitlement,
  reactivateUser,
  rejectAdminManualCheckout,
  rejectWithdrawal,
  resetIpaymuGatewayConfig,
  sendAdminMailTest,
  suspendUser,
  updateAdminApp,
  updateAdminMailSettings,
  updateAdminManualPaymentConfig,
  updateAdminPaymentGatewayConfig,
  updateAdminPlan,
  updateAdminPromo,
  updateAdminUserAppAccess,
  validatePromoCode,
} from './admin';
export {
  cancelProductPurchase,
  dismissOnboarding,
  downloadProductFile,
  getConsumerNotifications,
  getConsumerNotificationsUnreadCount,
  getConsumerProductBySlug,
  getConsumerProducts,
  getMyPurchases,
  getOnboardingTips,
  getProductPurchaseStatus,
  markAllConsumerNotificationsAsRead,
  markConsumerNotificationAsRead,
  purchaseProduct,
} from './consumer';
export {
  createLandingOrder,
  createLandingPage,
  createLandingPageBlock,
  deleteLandingPageBlock,
  getLandingBuilderPageStats,
  getLandingBuilderPerformance,
  getLandingBuilderStats,
  getLandingOrderDownload,
  getLandingOrderStatus,
  getLandingPageBlocks,
  getLandingPageCustomers,
  getLandingPages,
  getPublicBanners,
  getPublicLandingByDomain,
  getPublicLandingPage,
  getPublicLandingPageByOrganization,
  publishLandingPage,
  submitLandingCustomer,
  updateLandingPage,
} from './landing';
export {
  approveProductPurchase,
  createProduct,
  deleteProduct,
  deleteProductDoc,
  deleteProductFile,
  fetchAuthorizedBlobUrl,
  getAdminProductById,
  getAdminProductPurchases,
  getAdminProducts,
  getProductCategories,
  getPublicFlagshipApps,
  getPublicProductBySlug,
  getPublicProducts,
  publishProduct,
  refundProductPurchase,
  unpublishProduct,
  updateProduct,
  deleteProductBanner,
  uploadProductBanner,
  uploadProductDoc,
  uploadProductFile,
  uploadProductThumbnail,
} from './store';
export type { PublicFlagshipApp } from './store';
export {
  applyReward,
  calculateLoyaltyPoints,
  confirmPosOrderPayment,
  createPosCategory,
  createPosExperiencePromo,
  createPosExperienceSpace,
  createPosMember,
  createPosOrder,
  createPosOutlet,
  createPosProduct,
  createPosRewardRule,
  createPosTable,
  deletePosCategory,
  deletePosExperiencePromo,
  deletePosExperienceSpace,
  deletePosOutlet,
  deletePosProduct,
  deletePosRewardRule,
  deletePosTable,
  exportPosReport,
  getPosAccess,
  getPosCategories,
  getPosExperienceDashboard,
  getPosLoyaltyRewardRules,
  getPosLoyaltySettings,
  getPosMembers,
  getPosOrderReceipt,
  getPosOrders,
  getPosOutlets,
  getPosProducts,
  getPosReportDaily,
  getPosReportProducts,
  getPosReportSummary,
  getPosTables,
  getPublicOrganizationOutlets,
  lookupPublicPosMember,
  registerPublicPosMember,
  searchPosMembers,
  updatePosCategory,
  updatePosExperiencePromo,
  updatePosExperienceReservationStatus,
  updatePosExperienceSpace,
  updatePosLoyaltySettings,
  updatePosOrderStatus,
  updatePosOutlet,
  updatePosProduct,
  updatePosRewardRule,
  updatePosTable,
} from './pos';
export type {
  PosExperienceClaim,
  PosExperienceDashboard,
  PosExperienceMember,
  PosExperiencePromo,
  PosExperienceReservation,
  PosExperienceSpace,
  PosExperienceSpaceItem,
  PosOutlet,
  PosOutletListResponse,
  PosTableRecord,
} from './pos';
export {
  aiAssistArticle,
  createAdminClient,
  createAdminLandingArticle,
  createAdminLandingService,
  createAdminPortfolio,
  deleteAdminClient,
  deleteAdminLandingArticle,
  deleteAdminLandingService,
  deleteAdminPortfolio,
  getAdminClients,
  getAdminLandingContent,
  getAdminPortfolios,
  getPublicInsightBySlug,
  getPublicInsights,
  getPublicLandingContent,
  getPublicShowcaseClients,
  getPublicShowcasePortfolios,
  updateAdminClient,
  updateAdminLandingAbout,
  updateAdminLandingArticle,
  updateAdminLandingService,
  updateAdminPortfolio,
  uploadShowcaseMedia,
} from './content';
export type { LandingContent, ShowcaseClient, ShowcasePortfolio } from './content';
export type {
  AdminMailSettings,
  AdminPagination,
  AdminPaymentGatewayConfig,
  AdminPlan,
  AdminUserDetail,
  AdminUserListItem,
  EmailDeliveryResult,
  GatewayProviderCard,
} from './admin';
export type { EmailDelivery, OrganizationRef, TeamInvitation, TeamMember } from './organizations';
export type { PayoutPolicy, WalletBalance, WalletOverview, WalletTransaction, WalletWithdrawal } from './billing';
export type {
  PosCategoryRecord,
  PosOrderListItem,
  PosProductOption,
  PosProductOptionValue,
  PosProductRecord,
  PosReportDaily,
  PosReportPeriod,
  PosReportProducts,
  PosReportSummary,
} from './pos';
export type { OwnerNotification } from './admin';
export type { ConsumerNotification } from './consumer';
export type { PosMemberSearchResult } from './pos';
export type { HellomUser } from './auth';
export type { OrganizationSummary } from './organizations';
export type { PosAccessInfo } from './pos';
export type { PosLoyaltySettings, PosRewardRuleRecord } from './pos';
export type { PosReceipt } from './pos';
export type { AdminDashboardStats, AdminManualCheckout, AdminOrganizationListItem, AdminPayoutQueue, AdminPayoutQueueItem, PlatformFinanceSummary } from './admin';
export type { LandingBuilderPageStat, LandingBuilderPerformance, LandingBuilderStats, LandingPageRef } from './landing';
export type { PaymentGatewayStatus, PricingMatrixItem, PricingMatrixPlan } from './billing';
export type { LandingBlockRecord, LandingPageRecord } from './landing';
export type { CatalogAppItem } from './billing';
export type { MemberDashboardCard } from './member';

export {
  claimCustomerPromo,
  createCustomerOrder,
  createCustomerReservation,
  getCustomerMenu,
  getCustomerMenuByOrganization,
  getCustomerOrderStatus,
  getCustomerOrganizationOutlets,
  getCustomerTableOrders,
} from './posCustomer';
export type { CustomerOutlet, PosCustomerExperiencePayload, PosCustomerOutletStatus, PosMenuCategory, PosMenuOption, PosMenuPayload, PosMenuProduct, PosOrderItem, PosOrderPayload } from './posCustomer';
export {
  POS_ORDER_STATUS_LABELS,
  adjustPosMemberPoints,
  cancelPosOrder,
  exportPosMembers,
  getCustomerRealtimeToken,
  getPosFraudFlags,
  getPosMemberDetail,
  getPosMemberDuplicates,
  getPosMemberLedger,
  getPosMemberOrders,
  getPosMemberPage,
  getPosOutletSettings,
  getPosRealtimeToken,
  getPosTableBills,
  getPosTablesQrSheet,
  mergePosMembers,
  payPosTableBill,
  previewPosOrder,
  refundPosOrder,
  regeneratePosTableToken,
  resolvePosFraudFlag,
  updatePosOutletSettings,
} from './posOrders';
export type {
  PosCartLine,
  PosFraudFlag,
  PosLedgerRow,
  PosMemberDetail,
  PosMemberDuplicateGroup,
  PosMemberListParams,
  PosMemberRecord,
  PosOpeningSlot,
  PosOrderDraft,
  PosOrderStatus,
  PosOrderTotals,
  PosOutletSettings,
  PosOutletStatus,
  PosPaginated,
  PosQrTable,
  PosTableBill,
} from './posOrders';
export {
  checkInPosStaff,
  checkOutPosStaff,
  closePosStaffCash,
  createPosStaff,
  createPosStaffShift,
  deletePosStaff,
  downloadPosStaffExport,
  getPosStaffAttendanceQr,
  getPosStaffDashboard,
  invitePosStaffLogin,
  markLeavePosStaff,
  openPosStaffCash,
  regeneratePosStaffAttendanceQr,
  scanPosStaffAttendanceQr,
  updatePosStaff,
  updatePosStaffShift,
} from './posStaff';
export type { PosStaffAttendance, PosStaffAttendanceQr, PosStaffCashLog, PosStaffDashboard, PosStaffEmploymentStatus, PosStaffItem, PosStaffPermissionKey, PosStaffRole, PosStaffShift } from './posStaff';

export {
  getGuestCheckoutOptions,
  getGuestCheckoutStatus,
  magicLogin,
  resendGuestAccessEmail,
  startGuestCheckout,
} from './guestCheckout';
export type { GatewayPaymentInstructions, GuestCheckoutOptions, GuestCheckoutProduct, GuestCheckoutStartResult, GuestCheckoutStatus, ManualPaymentMethodOption } from './guestCheckout';

export {
  approveSellerWithdrawal,
  cancelSellerWithdrawal,
  downloadSellerWithdrawalProof,
  exportSellerFinance,
  getAdminReconciliation,
  getAdminSellerFinanceSummary,
  getAdminSellerWithdrawals,
  getAdminWebhookLogs,
  getLandingOrderPublicStatus,
  getSellerFinanceSettings,
  getSellerFinanceSummary,
  getSellerLedger,
  getSellerWithdrawals,
  markSellerWithdrawalFailed,
  markSellerWithdrawalPaid,
  reportLandingOrderReturn,
  requestSellerWithdrawal,
  updateSellerFinanceSeller,
  updateSellerFinanceSettings,
} from './sellerFinance';
export type {
  AdminReconciliation,
  AdminSellerFinanceSummary,
  AdminWebhookLog,
  AdminWithdrawalRow,
  LandingOrderStatus,
  SellerFinanceSettings,
  SellerFinanceSummary,
  SellerLedgerRow,
  SellerPayoutAccount,
  SellerWithdrawalRow,
} from './sellerFinance';

// Hellom Page selling (Fase 3): products, checkout, access page, orders, moderation.
export * from './landingStore';

// Hellom Page editor & marketing (Fase 4).
export * from './landingSite';
